In [1]:
import pandas as pd
from pathlib import Path
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [3]:
path = Path('../../data/expr_july/clf_levels_ADM_sents')

test = pd.read_pickle(path / 'test.pkl')

In [4]:
test.head()

,pad_sen_id,institution,year,MDN,NotitieID,batch,annotator,background_sent,target_sent,text_raw,labels,text,len_text,pred_levels_adm_sents
pad_sen_id,,,,,,,,,,,,,,
150256243_0073,150256243_0073,amc,2017,8309478,150256243,week_16,vervaart,False,False,5L,1.0,5L,1,0.917969
150256243_0074,150256243_0074,amc,2017,8309478,150256243,week_16,vervaart,False,False,O2 via nasale canule AF ( /min ):,1.0,O2 via nasale canule AF ( /min ):,8,1.045898
150256243_0075,150256243_0075,amc,2017,8309478,150256243,week_16,vervaart,False,False,"23 Auscultatie : Pleuravocht links , zachte to...",3.0,"23 Auscultatie : Pleuravocht links , zachte to...",23,0.678711
150404230_0070,150404230_0070,vumc,2017,Z3893942,150404230,week_18,meskers,False,False,"Algemeen : niet ziek ogend , slank , compos me...",4.0,"Algemeen : niet ziek ogend , slank , compos me...",33,4.078125
158325874_0005,158325874_0005,amc,2017,1195297,158325874,week_22-26,opsomer,False,False,"12 , lengte",4.0,"12 , lengte",3,4.437500